Clean up setup.py
StackStorm/st2-enterprise-sso-backend pull request #17
Opened 2023-03-14 05:53 UTC by cognifloyd

Drop problematic pip version check that can break pants/pex lockfile generation. Also, (if needed) update python classifiers to 3.6-3.8 and bump the version.

2023-03-18 12:25 UTC, arm4b requested changes

2023-03-20 21:46 UTC, cognifloyd commented on .circleci/config.yml
> +      DOCKER_DISTROS: bionic focal centos7 rockylinux8
sweet. I like to delete old stuff.

2023-03-22 20:44 UTC, arm4b approved these changes

2023-03-23 03:26 UTC, cognifloyd commented
This is a lot better. CI is still broken, but less so. I'm merging this, then someone else can work on fixing CI from this point

2023-03-23 03:26 UTC, merged